default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: simplify_dev
test:
  <<: *default
  database: simplify_test

production:
  <<: *default
  username: <%= ENV.fetch('USER') %>
  password: <%= ENV.fetch('PASSWORD') %>
  database: simplify_prod
