default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'default') %>
  database: <%= ENV.fetch('POSTGRES_DB', 'simplify_dev') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

test:
  <<: *default
  database: simplify_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'localhost') %>
