default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  database: <%= ENV.fetch('POSTGRES_DB', 'simplify_dev') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

test:
  <<: *default
  username: postgres
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  database: simplify_test
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'localhost') %>
