default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: simplify_dev
test:
  <<: *default
  database: simplify_test

production:
  <<: *default
  host: ENV.fetch('HOST')
  username: ENV.fetch('USER')
  password: ENV.fetch('PASSWORD')
  database: simplify_prod
