name: RSpec Runner

on:
  pull_request:
    branches:
      - main  # Adjust to match your target branch for PRs

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Replace with your Ruby version
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Run RSpec Tests
        run: bundle exec rspec
